docs/deployment/README.md
This PR will add documentation on how to deploy CB using Apache.
Considering adding docs about Database setup, but might leave it for another PR.
=> [Docs] Adding documentation for deployment with Apache

client/package-lock.json, client/package.json, client/src/containers/AddChart.js, client/src/containers/Chart.js, client/src/containers/ProjectBoard.js, client/src/containers/ProjectDashboard.js, server/controllers/ChartController.js, server/models/migrations/20191217204819-draft-chart.js, server/models/models/chart.js
This feature will help with building charts as the user can continue editing the chart at a later date and time.
=> Adding a Chart drafting feature

server/api/ChartRoute.js, server/api/ConnectionRoute.js, server/api/ProjectRoute.js, server/api/SavedQueryRoute.js, server/api/TeamRoute.js, server/api/UserRoute.js, server/controllers/ConnectionController.js, server/controllers/ProjectController.js, server/controllers/SavedQueryController.js, server/controllers/TeamController.js, server/controllers/UserController.js, server/models/migrations/20200106191652-user-admin-update.js, server/models/models/user.js, server/modules/verifyToken.js
This code can be used by Chartbrew to create charts from Chartbrew itself.
=> Added new routes in the API to fetch admin data - created admin role as well

.env-template, client/.eslintrc.json, client/package-lock.json, client/public/index.html, client/src/actions/user.js, client/src/components/LoginForm.js, client/src/config/settings.template.js, client/src/containers/Signup.js, docs/.vuepress/config.js, docs/oneaccount/README.md, package-lock.json, server/.eslintrc.json, server/api/UserRoute.js, server/controllers/AuthCacheController.js, server/controllers/UserController.js, server/index.js, server/models/migrations/20200120195521-create-auth-cache.js, server/models/migrations/20200122224335-update-user.js, server/models/models/authcache.js, server/models/models/user.js, server/modules/CleanAuthCache.js, server/package-lock.json, server/package.json
:sparkles: This PR adds the ability to log in/sign up using **One account**.
added `AuthCache`model migration to handle the authentication process through **One account**.
added `oneaccountId` to the `User` model in order to differentiate between account types which adds more control over the authentication process.
=> one account integration

client/public/index.html
new version of oneaccount contains number of internal improvements
=> :package: updated oneaccount library to the latest version

client/package-lock.json, client/public/index.html, client/src/actions/user.js, client/src/components/LoginForm.js, client/src/containers/Signup.js, docs/oneaccount/README.md, package-lock.json, server/api/UserRoute.js, server/index.js, server/package-lock.json, server/package.json
:package: updated to the latest oneaccount package version 3.1.3 
:package: added oneaccount-express to improve the clarity of the backend code.
:recycle: small refactoring to accomodate the update of packages
:pencil: updated docs to reflect the changes
=> Oneaccount update

client/.gitignore, client/.lintstagedrc.json, client/package-lock.json, client/package.json, lerna.json, package-lock.json, package.json, server/.gitignore, server/.lintstagedrc.json, server/package-lock.json, server/package.json
Hi, @razvanilin
Related Issue #47 
I did a setup using these tools:
- [lerna](https://github.com/lerna/lerna) - managing multi directories eg. client and server
- [lint-staged](https://github.com/okonet/lint-staged) - run lint to staged files
- [husky](https://github.com/typicode/husky) - for git hooks
Here's the screenshot for the test that I did. 
**With lint error**
**Without error**
**NOTE:**
I'm not 100% with the setup of `lerna` since it's my first time setting up a project with multi directories (having 2 different package.json), since git hook _somewhat_ only allow 1 instance and will ignore the other one. That's the whole the reason I used `lerna`. Just give this a try. 
I'm happy to help. 
Just let me know if you need anything else.
=> Add pre-commit hook eslint auto fixed

client/src/components/ApiPagination.js
=> refactor component ApiPagination into functional component

client/src/components/EditUserForm.js
=> refactor component EditUserForm into functional component

client/src/components/FeedbackForm.js
=> refactor component FeedbackForm into functional component

client/src/components/InviteMembersForm.js
=> refactor component InviteMembersForm into functional component

client/src/components/Navbar.js
for https://github.com/chartbrew/chartbrew/issues/58
=> Refactor Navbar component into functional component

client/src/components/SavedQueries.js
for https://github.com/chartbrew/chartbrew/issues/58
=> Refactor SavedQueries component into functional component

client/src/components/Invites.js
=> refactor component Invites into functional component

client/src/containers/Main.js
=> 🔨 refactor Main component

client/src/containers/PasswordReset.js
=> refactor container PasswordReset to functional component

client/src/containers/VerifyUser.js
Based on #58. This is my first pull-request for a React project, please review when you have time. Thank you!
=> Refactor VerifyUser to use react-hooks

client/src/containers/Login.js
Just wanted to help out as a part of the #58 and get to know the project a bit better.
=> Refactor login container to use hooks

Dockerfile
Move to node v14 to correct dependency issues with modules.
See:  https://github.com/chartbrew/chartbrew/issues/127
=> Update Dockerfile to Node 14-slim

client/src/components/Navbar.js, client/src/containers/ProjectBoard/ProjectBoard.js
I added the dashboard name 
when clicking the collapse menu, the dashboard name will show
=> Add the dashboard name in the Navbar

client/src/components/HelpBanner.js, client/src/containers/Connections/Customerio/CustomerioConnectionForm.js, client/src/containers/Connections/Firestore/FirestoreConnectionForm.js, client/src/containers/Connections/GoogleAnalytics/GaConnectionForm.js, client/src/containers/Connections/RealtimeDb/RealtimeDbConnectionForm.js, client/src/containers/Connections/components/ApiConnectionForm.js, client/src/containers/Connections/components/MongoConnectionForm.js, client/src/containers/Connections/components/MysqlConnectionForm.js, client/src/containers/Connections/components/PostgresConnectionForm.js
I already added a help banner in connections with dark mode and light mode
=> Add a help banner in connections

client/src/components/Navbar.js
I linked the dashboard name to dashboard URL in the navbar
=> Link dashboard name to dashboard URL in navbar

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/DatasetFilters.jsx, client/src/config/gridBreakpoints.js, client/src/containers/AddChart/components/ChartDatasetConfig.jsx, client/src/containers/Chart/Chart.jsx, client/src/containers/Chart/components/ChartFilters.jsx, client/src/containers/Dataset/Dataset.jsx, client/src/containers/Dataset/DatasetBuilder.jsx, client/src/containers/EmbeddedChart.jsx, client/src/containers/Main.jsx, client/src/containers/ProjectBoard/components/ProjectNavigation.jsx, client/src/containers/ProjectDashboard/ProjectDashboard.jsx, client/src/containers/ProjectDashboard/components/Filters.jsx, client/src/containers/PublicDashboard/PublicDashboard.jsx, client/src/containers/Variables/Variables.jsx, client/src/modules/useChartSize.js, client/src/slices/project.js, client/src/slices/team.js, server/api/ProjectRoute.js, server/controllers/ProjectController.js, server/controllers/TemplateController.js, server/models/migrations/20240419063042-create-variable-table.js, server/models/models/project.js, server/models/models/variable.js, server/templates/custom/builder.js
The new filters will work the same as before, but will have the added functionality of having variables attached to them. Variables can be used when embedding charts or when using dashboard filters. This means you can assign the same variables to multiple chart filters and then filter all of them at dashboard-level.
Checklist:
=> Upgrade chart and dashboard filters to use variables

.env-template, docker-compose.yml
=> Improve docker-compose file for beginners, add some info on docker networking in `.env-template`

client/src/containers/ProjectDashboard/ProjectDashboard.jsx, client/src/containers/TeamMembers/TeamMembers.jsx
just follow your code, add a filter.
but I am curious why not just filter ghost project in here
```
// ProjectController.js
getTeamProjects(teamId) {
return db.Project.findAll({
where: { team_id: teamId } //  add ghost or name filter here
```
=> filter ghost project in the access modal & hide create chart button for projectViewer

client/package-lock.json, client/package.json, client/src/containers/AddChart/components/SqlBuilder.jsx, client/src/containers/AddChart/components/VisualSQL.jsx, client/tailwind.config.js, server/controllers/ConnectionController.js, server/models/migrations/20240609052207-add-schema-connection.js, server/models/models/connection.js
Add a no-code interface for querying MySQL and Postgres connections. This removes the need to know SQL to query data, but the full SQL query editor will still be available for more advanced use-cases.
=> Create a visual SQL UI for MySQL and Postgres dataset queries

client/src/containers/Dataset/DatarequestSettings.jsx
Error is dataset.id not exist.
=> Fix the flash error that appear when clicking the create dataset button.

docker-compose.yml
Not sure if this fits with the rest of the project.
It makes things easier to use the dynamically allocated address from Docker.
=> Move to host addresses from .env to compose file to reflect dynamic Docker address

client/package-lock.json, client/package.json, client/src/containers/Chart/Chart.jsx, client/src/containers/ProjectDashboard/ProjectDashboard.jsx, client/src/containers/PublicDashboard/PublicDashboard.jsx, client/src/containers/PublicDashboard/components/SharingSettings.jsx, client/src/slices/project.js, server/controllers/ProjectController.js, server/models/migrations/20241215101615-change-onreport-chart-default.js, server/models/models/chart.js
* All charts are added to the report by default
* Re-design the Sharing UI to make it easier to use
* Place the sharing functionality directly on the main dashboard
=> Simplify the reporting feature in Chartbrew

.env-template, client/src/containers/AddChart/components/SqlBuilder.jsx, client/src/containers/Connections/ConnectionWizard.jsx, client/src/containers/Dataset/AiQuery.jsx, client/src/containers/Dataset/DatasetQuery.jsx, client/src/modules/availableConnections.js, server/api/DataRequestRoute.js, server/controllers/DataRequestController.js, server/modules/ai/generateSqlQuery.js, server/package-lock.json, server/package.json
SQL-based connections such as MySQL, Postgres, Amazon RDS, etc have a conversation UI in the dataset builder.
Users can ask AI to generate a query from scratch or edit existing queries in a conversation-like manner.
=> Added the option to converse with AI to generate and edit SQL queries

client/src/containers/AddChart/components/ChartPreview.jsx, client/src/containers/Chart/Chart.jsx, client/src/containers/Chart/components/GaugeChart.jsx, server/models/migrations/20250213071751-add-ranges-chart.js, server/models/models/chart.js
=> ✨ Adding Gauge charts to Chartbrew

client/src/containers/ProjectDashboard/components/UpdateSchedule.jsx
Fixes: #273 
- considers "timezone" from projects "updateSchedule" too
=> fix: restore timezone from updateSchedule

client/src/containers/AddChart/components/MongoQueryBuilder.jsx, client/src/containers/Connections/components/MongoConnectionForm.jsx, client/src/containers/Dataset/AiQuery.jsx, client/src/containers/Dataset/DatasetQuery.jsx, client/src/modules/availableConnections.js, client/src/slices/connection.js, server/api/ConnectionRoute.js, server/controllers/ConnectionController.js, server/controllers/DataRequestController.js, server/crons/workers/updateMongoSchema.js, server/index.js, server/modules/ai/generateMongoQuery.js, server/setUpQueues.js
* Added a new module to infer the MongoDB databases schemas
* Added a new worker to update the schema that can be queued with bullmq
* Update the MongoDB dataset UI to give the user the option to ask AI to generate queries
=> :sparkles: added AI query assistant for mongodb datasets

client/src/config/gridBreakpoints.js, client/src/containers/ProjectDashboard/ProjectDashboard.jsx
* When the layout editor is toggled, the user can preview and change the layout in all breakpoints
=> :sparkles: Introducing a layout editor to edit all breakpoints

client/src/components/EditUserForm.jsx, client/src/containers/TeamMembers/TeamMembers.jsx, client/src/containers/TeamSettings.jsx, client/src/containers/UserDashboard/UserDashboard.jsx, client/src/slices/team.js, server/api/TeamRoute.js, server/api/UserRoute.js, server/controllers/TeamController.js, server/controllers/UserController.js, server/models/models/teamrole.js, server/modules/accessControl.js
Allow users to own and create multiple teams:
=> :sparkles: Users can create multiple teams

server/controllers/DataRequestController.js, server/controllers/DatasetController.js
Postgres needs specific casting for the includes
=> :bug: Fix VariableBinding includes for running with Postgres

client/src/containers/AddChart/AddChart.jsx, client/src/containers/Dataset/Dataset.jsx, client/src/containers/ProjectDashboard/ProjectDashboard.jsx, client/src/modules/autoLayout.js, docs/specs/FS-20250924-auto-layout.md
Auto-layout feature for the layout editor to remove the manual editing for all breakpoints
- FS-20250924-auto-layout
=> :sparkles: added auto-layout to the dashboard layout editor
